name: WallJump
version: 2.0.3
main: me.arthed.walljump.WallJump
api-version: 1.19
softdepend: [WorldGuard, TreysDoubleJump]
authors: [ Arthed, MonsterWhat ]
description: Adds an easy to understand, yet still challenging wall jump mechanic
commands:
  walljump:
    aliases: [wj, wjump]
