name: WallJump
version: 4.0.0
main: com.playdeca.walljump.WallJump
api-version: 1.20
softdepend: [WorldGuard, TreysDoubleJump]
authors: [ Arthed, MonsterWhat ]
description: Adds an easy to understand, yet still challenging wall jump mechanic
commands:
  walljump:
    aliases: [wj, wjump]
